language: ruby
cache: bundler
bundler_args: --without development doc

before_install:
  - gem update --system
  - gem --version

rvm:
  - jruby-9.2.5.0
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  fast_finish: true

jobs:
  include:
    - stage: linting
      rvm: ruby-2.4.1 # Pre-installed on TravisCI
      install: true # Do not bundle install
      script: gem install rubocop --no-document && rubocop

stages:
  - linting
  - test

branches:
  only:
    - master
